// src/version.ts
// AXIS-VIEW 버전 관리 — Semantic Versioning (OPS 동일 기준)

export const APP_VERSION = 'v1.45.1';
export const BUILD_DATE = '2026-05-18';

// 버전 이력
// v1.0.0 | 2026-03-06 | Sprint 1~3     | 초기 릴리스 (로그인, 출퇴근 대시보드, 실 API 연동)
// v1.1.0 | 2026-03-08 | Phase 2        | QR 관리 페이지 (상태바, 날짜 필터, CSV 추출)
// v1.2.0 | 2026-03-11 | Phase 2-2~3    | 공지사항, ETL 변경이력, 컨셉 HTML 매칭 4개 페이지
// v1.3.0 | 2026-03-11 | Phase 3-A      | 알림 뱃지 (Header+Sidebar) + Admin prefix 로그인
// v1.4.0 | 2026-03-11 | Phase 4        | Role 기반 접근 제어 + 권한 관리 페이지
// v1.4.1 | 2026-03-11 | Phase 4-fix    | Toggle API endpoint 수정 + Manager 자사 필터
// v1.4.2 | 2026-03-12 | BUG-1 fix      | Logout Storm 수정 (401 무한 루프 방지)
// v1.5.0 | 2026-03-12 | Phase 5-A      | 협력사 관리 메뉴 개편 + 대시보드/평가지수/물량할당 페이지 + 근태 자사 필터
// v1.5.1 | 2026-03-12 | Phase 5-A+     | 생산관리 메뉴 개편 (생산일정/생산실적/출하이력)
// v1.6.0 | 2026-03-13 | Sprint 27 연동 | 권한 매트릭스 세분화 (GST 일반/협력사 manager 분리)
// v1.6.1 | 2026-03-15 | ETL 개선       | O/N 컬럼 추가 + pi_start 변경 추적 + summary limit 수정
// v1.7.0 | 2026-03-16 | Sprint 29 연동 | 공장 API 실데이터 연동 + 대시보드/생산일정 리팩토링
// v1.7.1 | 2026-03-16 | UX 개선        | 공장 대시보드 자동 새로고침 + 근태 근무지 컬럼
// v1.8.0 | 2026-03-18 | Sprint 5       | QR DUAL Tank 뱃지 + 기구/모듈 필터 분리 + ETL 오늘 필터 + Order No 검색 + 슬라이드 정지/재생
// v1.9.0 | 2026-03-20 | Sprint 6~8     | 태스크 진행률 + 카테고리 필터 + 사용자 분석 대시보드 + 생산실적 API 연동
// v1.10.0| 2026-03-23 | Sprint 13      | 생산실적 공정 그룹 탭 분리 (기구·전장 / TM) + vitest 테스트 환경 구축
// v1.11.0| 2026-03-23 | Sprint 14      | 혼재 O/N partner별 실적확인 UI + 일괄확인 혼재 제외
// v1.12.0| 2026-03-23 | Sprint 15      | #36-C TM 가압검사 옵션 UI (ConfirmSettingsPanel TM 그룹 박스)
// v1.13.0| 2026-03-24 | Sprint 16      | S/N별 실적확인 UI + TM 혼재 제거 + 탭별 End 필터 + SNConfirmButton
// v1.13.1| 2026-03-24 | Sprint 17      | HOTFIX: end 필터 sns 순회 + inline 중복 제거 + keepPreviousData
// v1.14.0| 2026-03-25 | Sprint 18      | S/N 작업 현황 카드뷰 (생산현황 페이지 + 상세 패널)
// v1.15.0| 2026-03-26 | Sprint 20      | 체크리스트 관리 목업 + 생산현황 체크리스트 연동
// v1.15.1| 2026-03-27 | Sprint 18-B    | S/N 상세뷰 UX 개선 (작업자 정렬 반전 + 체크리스트 토글 + task 이름 표시 + API 경로 수정)
// v1.15.2| 2026-03-27 | Sprint 18-B+   | 생산현황 공정 탭 제거 + 협력사 권한 필터 + 준비중 태그 제거
// v1.15.3| 2026-03-27 | Sprint 18-C    | 상세뷰 다중 task 병합 렌더링 + task_name 표시
// v1.16.0| 2026-03-28 | Sprint 40-C    | 비활성 사용자 관리 페이지 (30일 미로그인 + 비활성화/재활성화)
// v1.16.1| 2026-03-28 | Sprint 40-C+   | Manager 비활성화 요청 기능 (권한 관리 → 자사 소속 비활성화 요청 + admin 알림)
// v1.17.0| 2026-03-29 | Sprint 21      | 반응형 레이아웃 (사이드바 접기 + KPI/차트 media query + 모바일 오버레이)
// v1.17.1| 2026-03-30 | Sprint 22      | 공정 완료 판정 버그 수정 (categories 기준 통일)
// v1.18.0| 2026-03-30 | Sprint 23      | Task 재활성화 UI (생산현황 S/N 디테일)
// v1.19.0| 2026-03-31 | Sprint 24      | 생산현황 O/N 섹션 헤더 + 검색 확장
// v1.20.0| 2026-04-01 | Sprint 25      | 페이지별 설정 패널 (테스트 S/N 토글 + TM 체크리스트 옵션)
// v1.21.0| 2026-04-02 | Sprint 26      | 체크리스트 관리 BE 연동 + TM 활성화 + 토글 확인 다이얼로그
// v1.22.0| 2026-04-03 | Sprint 27      | 월마감 캘린더 뷰 + 이름 마스킹
// v1.23.0| 2026-04-03 | Sprint 28      | 체크리스트 성적서 + 생산실적 폰트/명칭 개선 + ISO주차 수정
// v1.24.0| 2026-04-07 | Sprint 28+     | QR 이미지 모달 + Digital Twin 목업 + CT 분석 카드 통일
// v1.25.0| 2026-04-09 | Sprint 29~30   | QR 전장시작 필터 + 비활성화 권한 분기 + 422 에러 처리
// v1.26.0| 2026-04-10 | Sprint 30+     | 성적서 ELEC Phase/TM DUAL/SELECT/QI + 체크리스트 그룹 정렬
// v1.27.0| 2026-04-14 | Sprint 31      | ELEC 체크리스트 VIEW 연동 (상세뷰 진행률 + 관리 블러 해제)
// v1.28.0| 2026-04-15 | Sprint 31+     | 생산일정 업체 필터 + 체크리스트 ELEC 정렬/UI 수정
// v1.29.0| 2026-04-16 | QR 개선        | QR 관리 전장협력사 컬럼 + 필터
// v1.30.0| 2026-04-16 | Sprint 32      | 체크리스트 관리 ELEC 항목 추가/수정 + Sprint 60-BE 연동
// v1.31.0| 2026-04-17 | Sprint 33      | 미종료 작업 관리 (강제종료 + 미시작 표시 + 권한)
// v1.32.0| 2026-04-17 | HOTFIX-04/FE-19| ProcessStepCard 강제종료 placeholder 렌더 + formatDateTime 유틸 승격
// v1.32.1| 2026-04-18 | FE-19.1 후속   | per-row 강제종료 표시 — 상태 컬럼 '🔒 강제종료 mm/dd hh:mm' 대체 + 툴팁 + 데드 코드 정리
// v1.32.2| 2026-04-18 | FE-19.2 후속   | 강제종료 툴팁 즉시 반응 (browser title 딜레이 회피) — CSS .fc-tooltip + data-tooltip 패턴
// v1.32.3| 2026-04-20 | FE-19.1 용어정합| 강제종료 툴팁 '종료:' → '종료 처리:' (클린 코어 원칙 #4 UI 책임 — 감사 시각 명시)
// v1.33.0| 2026-04-20 | Sprint 34      | S/N 상세뷰·O/N 헤더 정보 보강 (FE-20 카테고리 회사명 + FE-21 line) — BE FIX-25 v4 연동
// v1.34.0| 2026-04-22 | Sprint 35      | 공장 대시보드 KPI 주간/월간 스와이프 덱 + KpiCard 공용화 + pipeline.shipped→shipped_count 마이그레이션 — OPS Sprint 62-BE 연동
// v1.34.1| 2026-04-22 | Sprint 35 HOTFIX| monthly-detail date_field 'finishing_plan_end'→'mech_start' 복원 (BE Sprint 62-BE 미배포로 생산 현황 상세·월간 지표 0건 발생) — BE 배포 후 재전환 예정
// v1.34.2| 2026-04-22 | TEMP-HARDCODE   | 손님 응대용 임시 하드코딩 — 주간 11대 / 월간 76대 (W17 / 2026-04 actual_ship_date 기준) — BE Sprint 62-BE 배포 후 제거 필수
// v1.34.3| 2026-04-22 | TEMP-HARDCODE fix| 주간 생산량 BE 동적 값 복원 (v1.34.2에서 실수로 하드코딩 덮었음) + 월간 생산량 215 / 월간 출하 76 분리 유지
// v1.34.4| 2026-04-23 | 문서 정정       | mech_start 영구 유지 확정, finishing_plan_end 재전환 계획 폐기 — CHANGELOG/주석/설계서 3곳 정정 (Sprint 36 옵션 토글 예정)
// v1.34.5| 2026-04-23 | HOTFIX S3       | KPI 덱 탭 전환 버그 수정 (handleScroll clientWidth=0 방어) + 30초 자동 전환 (autoSwipeInterval prop)
// v1.34.6| 2026-04-23 | HOTFIX S2       | scroll-snap 방식 실효 안됨 → transform: translateX 재설계 — 탭/자동 전환 확실 동작 확보
// v1.35.0| 2026-04-23 | Sprint 35 P2    | BE Sprint 62-BE v2.2 연동 — TEMP-HARDCODE 제거 + 출하 3필드(plan/actual/ops) + 월간 date_field 토글 + FactoryDashboardSettingsPanel 신규
// v1.35.1| 2026-04-23 | HOTFIX 매핑정정  | 생산현황 상세 "출하예정" 컬럼 매핑 정정 (finishing_plan_end → ship_plan_date) — 라벨 정합성
// v1.35.2| 2026-04-25 | HOTFIX 권한 분기  | 체크리스트 관리 페이지 협력사(비-GST) 읽기 전용 — canEdit = is_admin || company==='GST' (항목추가·설정·행클릭·토글 차단 + 툴팁)
// v1.36.0| 2026-04-27 | Sprint 37        | S/N 작업 현황 O/N 그룹 카드 인라인 토글 — 다대(2대+) 그룹 헤더 클릭 펼침/접힘 + 검색 자동 펼침(lastProcessedSearchRef race 방지) + 상세패널 자동 펼침 + stale key cleanup. BE 의존 0, SNStatusPage.tsx 단일 파일 (319→424 LOC). Codex 1차 4건+2차 1건 전건 반영
// v1.36.1| 2026-04-27 | UX 일관성        | O/N 그룹 토글 통일 — 단대/다대 분기 제거. salesOrder 있는 모든 그룹이 동일하게 클릭 토글 (Sprint 37 운영 후 일관성 피드백 반영). multi → hasHeader 변경, SNStatusPage.tsx 424→421 LOC
// v1.36.2| 2026-04-27 | REF-V-00-UTIL    | formatDate 공통 유틸 승격 (REFACTOR-FMT-01 완성) — utils/format.ts 에 fallback 인자 + invalid Date 가드 통합. QrManagementPage / InactiveWorkersPage 로컬 함수 2건 제거. 사용자 화면 변화 0 (순수 내부 정리)
// v1.37.0| 2026-04-28 | Sprint 36        | 출하 토글 3옵션 재구조 (BE Sprint 62-BE v2.4 대응) — ShippedBasis: 'ops' → 'best' 교체. shipped_best 필드 추가, shipped_ops 폐기 표시. SettingsPanel 라디오 라벨 '실시간(ops)' → '종합(best)'. localStorage 'ops' 저장값 → 'actual' 마이그레이션. BE 미배포 동안 'best' 선택 시 undefined → '—' 표시 (안전 degrade)
// v1.38.0| 2026-04-30 | Sprint 38        | S/N 작업 현황 진행 중 모델별 카운트 칩 + 미니 진행 바 — 검색바 아래 칩 그룹 (linear-gradient 진행 바 효과). InProgressModelChips.tsx 신규 추출 (코드 크기 원칙 위반 차단). modelFilter 별도 state (Codex M1: 정확매칭, search 부분매칭과 분리). Effect 4 자동 펼침 (Sprint 37 패턴). CLS 완화 minHeight, 모델 키 정규화(trim), aria 강화
// v1.40.0| 2026-05-04 | Sprint 40        | TM Tank Module 시작/종료 admin 액션 + O/N 일괄 토스트 — SNDetailPanel 카테고리 카드 아래 inline 버튼 (▶/■). P2 화이트리스트 (TMS+MECH) — GAIA/iVAS + DRAGON/SWS/GALLANT 자동 흡수. useGetTasksByOrder query hook + 4 mutation hook (start/complete + batch ×2, Optimistic + retry: 1). useEscapeKey/DialogActions/ParallelConfirmDialog 신규. utils.ts 카테고리별 회사 매핑 (M6 c-3 NULL 경고). Codex 1~5차 47건 전건 반영. BE Sprint 64-BE 미배포 시 Promise.allSettled fallback (안전 degrade)
// v1.41.0| 2026-05-04 | Sprint 39        | MECH 체크리스트 VIEW 연동 — OPS Sprint 63-BE 의 MECH 체크리스트 BE 인프라 (migration 051+051a v2, check_mech_completion, routes/checklist.py MECH 분기) 활용. 5 파일 변경: BLUR_CATEGORIES MECH 제거 (ChecklistManagePage + ChecklistFilterBar 두 곳), TYPE_OPTIONS.MECH SELECT 추가, isMech 분기 (payload + 토글 렌더 JSX), MECH_GROUP_DEFAULTS 8 그룹 자동 추론, 라벨 카테고리 무관 일반화 ("1차 입력 적용" / "QI 검사 필요"). EditModal/Table 도 MECH 분기 추가 (UX 대칭). Sprint 32 ELEC 패턴 재활용 (DRY). Codex 1~3차 19건 전건 반영. ~50 LOC
// v1.41.1| 2026-05-04 | Sprint 39 후속    | MECH 카테고리 COMMON product 자동 매핑 — BE migration 051a v2 의 MECH 마스터 모두 product_code='COMMON' 시드. ChecklistManagePage 에 COMMON_CATEGORIES 상수 신설 (TM/ELEC/MECH 통합), effectiveProduct 자동 'COMMON' 매핑 (MECH 카테고리 데이터 정상 조회 보장). hideProductDropdown 도 동일 상수 사용 (UX 일관성 — MECH 도 dropdown 숨김 처리, 선택 의미 없는 비활성 dropdown 노출 방지). v1.41.0 push 직후 사용자 후속 보강 + UX 일관성 정정
// v1.42.0| 2026-05-06 | Sprint 41         | 협력사별 진행률 view (BIZ-COMPANY-PROGRESS-01) — admin/GST 현행, 협력사 자기 담당 카테고리(MECH/ELEC/TMS)만 평균. utils/companyScopedProgress.ts 신규 (getCompanyScopedPercent + getCompanyScopedCategories + PARTNER_FIELD_ALIASES TMS(M)/(E) 정규화 + DB 빈문자 가드). SNCard / SNStatusPage (groupedByON null 가드 + sort rank null=3 + inProgressByModel 회사 뷰) / SNDetailPanel 분기. 12 케이스 단위 테스트 신규. BE 의존 0 (Sprint 34 partner 필드 활용). Claude 1·2차 + Codex 1·2차 누적 약 41건 합의. ~214 LOC, 5 파일 (utils 1 + components 3 + test 1)
// v1.43.0| 2026-05-09 | Sprint 42         | 자재 마스터 + 체크리스트 자재 매핑 admin GUI (FEAT-AXIS-VIEW-MATERIALS-AND-CHECKLISTS-MGMT-20260507) — OPS Sprint 66-BE Step 4 별 repo 분리. /materials 신규 페이지 (CRUD + Excel 4단계 업로드 미리보기 diff + 가스 ILIKE 검색) + /checklist 기존 확장 (SELECT 항목 [매핑] 버튼 → ChecklistOptionMapModal). 신규 6 파일 (MaterialsPage 290 / 모달 4종 691 / api 116) + 수정 5 파일 (App / Sidebar / api/checklist 확장 / ChecklistTable / ChecklistManagePage). 1,173 LOC 실측 (~955 추정 +23%, 1단계 한도 내). 권한 admin/GST (M6-A). 자재 비활성화 = warn + keep (M-NEW-4-B). select_options round-trip = string[]|number[] union (M-NEW-3). FormData multipart + UTF-8/CP949 fallback (M-NEW-1·2). Codex 1·2차 + Claude 1~4차 누적 약 36건 합의 (Codex M-2차-2 산수 오류 REJECT)
// v1.43.2| 2026-05-11 | PATCH 정렬 정합   | 협력사 관리 > 체크리스트 성적서 (ChecklistReportView) 항목 정렬 — ChecklistManagePage 와 동일 패턴 (그룹 첫 등장 순 + item_order). 배경: OPS BE checklist_service.py L235-239 ORDER BY CASE 절에 MECH 그룹 누락 (ELSE 99 = 정렬 미적용), TM/ELEC 만 명시 — Twin파파 catch. FE 단독 정정: ChecklistReportItem type 에 item_order? 추가 + CategoryTable 에 useMemo sort 추가 (manage 패턴 차용). 3 파일 / ~25 LOC (types/checklist +1 / ChecklistReportView +20 / version.ts). 빌드 GREEN + vitest 45/45 PASS
// v1.43.3| 2026-05-11 | HOTFIX UX 보강    | 체크리스트 항목 추가 CONFLICT 토스트 보강 — handleAdd onError 가 BE 응답 (existing_id + is_active) 활용. 비활성 충돌 시 토글 안내 메시지 자동 첨부. 실패 시 모달 유지 (입력값 보존). OPS HOTFIX-SPRINT66BE-CREATE-MASTER-ITEM-TYPE-AND-CONFLICT-MSG-20260511 BE 정합. ~22 LOC / 1 파일 (ChecklistManagePage.tsx handleAdd). 회귀 0 (응답 무 CONFLICT 시 generic message fallback)
// v1.43.11| 2026-05-15 | MECH 1차+2차 검수 합산 + 상세 폰트 | 생산현황 상세화면 MECH 체크리스트가 1차 검수(phase 1) 11개만 카운트되고 2차 검수(phase 2) 미포함 (Twin파파 catch). 원인: getChecklistStatus() 가 BE status/detail 엔드포인트를 phase 파라미터 없이 호출 → BE 기본값 phase=1 만 조회. MECH 체크리스트는 BE 에서 1차 검수(작업자)/2차 검수(관리자 보강) 2개 phase 로 분리, 완료 판정 check_mech_completion_all() = phase1 AND phase2. fix: getMechChecklistCombined() 신규 — MECH 는 status/detail 각각 phase 1·2 분리 호출(4건) → summary 합산 + items 병합(그룹 접두어 '1차 ·'/'2차 ·' + master_id offset 으로 React key 충돌 회피). flattenChecklistDetail() 헬퍼 추출 (ELEC/TM 단일 호출 경로도 공용). + 상세화면 폰트 +1px (SNDetailPanel/ProcessStepCard, 9~15px→10~16px — Twin파파 "너무 작아서"). 4 파일 (api/checklist.ts + checklist.test.ts 10 TC + SNDetailPanel + ProcessStepCard). BE 변경 0. Codex 확인 라운드 GO (M 0건, A-1 ui_key 분리 BACKLOG 이관). 빌드 GREEN + vitest 62/62 PASS
// v1.44.1 | 2026-05-18 | Sprint 44 후속 검토 fix | Sprint 44(v1.44.0) 자가 검토 catch 3건 반영. (1) ProductionChart 옵션 E — 도넛 카드가 더 커서 생긴 좌측 막대차트 빈 공간 → flex stretch 로 매칭 (병행 세션 작업 커밋 + 막대 % height). (2) #3 막대 위 count 숫자가 컬럼 최상단 고정되던 것 → 막대 wrapper 안으로 이동, 막대 높이 따라가게 (Twin파파 결정). (3) FactoryDashboardPage handleRefreshAll 에 monthlyDonut refetch 누락 → 추가 (전체 새로고침 시 도넛 갱신). (4) useMonthlyDetail 에 placeholderData: keepPreviousData 추가 (date_field 토글 전환 깜빡임 완화 — useMonthlyKpi 동일 패턴). 3 파일 (ProductionChart / FactoryDashboardPage / useFactory). 빌드 GREEN + vitest 72/72. 동반 OPS #69 — 월간 생산량 KPI TEST CUSTOMER 제외 (169→164, 도넛 정합, BE 요청)
// v1.44.0 | 2026-05-18 | Sprint 44 — 공장 대시보드 고객사 도넛 | 공장 대시보드 우측 패널을 주간/월간 토글에 연동 — 월간 뷰에서 "월생산 고객사 비율" 도넛 차트 표시 (Twin파파 요청). 별도 타이머 없이 기존 KpiSwipeDeck 30초 period 토글 편승. 주간=공정별 완료율(기존)/월간=고객사 도넛. 도넛: Recharts PieChart, Top5 고객사 + 기타 합산(6조각 상한), TEST CUSTOMER FE 제외, 중앙 총 생산대수, G-AXIS 색상. 데이터=OPS #68 monthly-detail by_customer 집계 (BE 배포 완료 factory.py L281-292). A2 분기 방식: 도넛 전용 useMonthlyDetail 별도 호출(date_field=monthlyDateField, per_page:1) — 테이블/차트용 mech_start 호출 불변 → v1.34.4 유지, 회귀 0. 신규 2 파일 (CustomerDonutCard 신규 도넛 + buildDonutSlices 순수함수 / StageCompletionCard 인라인 추출) + 수정 3 (api/factory.ts CustomerCount+by_customer? / useFactory.ts useMonthlyDetail enabled / FactoryDashboardPage period 분기+도넛 호출) + 테스트 CustomerDonutCard.test.ts 8 TC. Codex 1라운드 M3/A3/I5 → 영역 8 전건 반영 + A2 분기 재확정. 빌드 GREEN + vitest 72/72 PASS. 번들 +4.77kB
// v1.43.14| 2026-05-18 | QR CSV 협력사 컬럼 추가 | QR 관리 페이지 CSV 다운로드에 mech(기구협력사) + elec(전장협력사) 컬럼 추가 (Twin파파 요청). CSV 는 FE 생성 방식 (QrManagementPage.tsx downloadCsv) — OPS QR 목록 API(/api/admin/qr/list)가 mech_partner/elec_partner 이미 응답 (qr.py p.mech_partner/p.elec_partner SELECT). exportItems 가 QrRecord[] 전체 유지 → partner 접근 가능. fix 3줄: downloadCsv signature 타입 확장 + header 'QR_DOC_ID,SN,O/N' → '...,mech,elec' + 행 매핑 2필드 추가 (mech_partner/elec_partner ?? ''). 1 파일 (QrManagementPage.tsx). BE 변경 0. Codex 라운드 1 M=0/A=3/N=5 (blocker 0 — A: sales_order CSV escape 기존 이슈 / vitest 부재 / optional signature ?? fallback). tsc -b 에러 0 + vite build GREEN. 회귀 0 (additive — CSV 컬럼 2개 추가, 기존 3컬럼 영향 0)
// v1.43.13| 2026-05-16 | 체크리스트 성적서 검색 정합 | 협력사 관리 > 체크리스트 성적서 검색 — O/N 은 숫자만 입력해도 나오는데 S/N 은 영문 prefix 까지 쳐야 나오던 비대칭 fix (Twin파파 catch). 원인: api/checklist.ts searchSNList() 가 `/^[A-Z]{2,5}-/` 정규식으로 query 를 O/N(sales_order) 또는 S/N(serial_number) 중 하나로만 라우팅 → 숫자만 입력 시 항상 sales_order 검색으로만 감 → S/N 검색 누락. BE 엔드포인트(/api/admin/checklist/report/orders)는 sales_order + serial_number 동시 전송 시 OR 조건 + serial_number ILIKE 부분 매칭 이미 지원. fix: regex 분기 제거 → 두 파라미터 항상 동시 전송. 이제 숫자 일부만 입력해도 O/N·S/N 양쪽 검색됨. 1 파일 (api/checklist.ts ~3 LoC) + checklist.test.ts TC 2건. BE 변경 0. 빌드 GREEN + vitest 64/64 PASS
// v1.43.12| 2026-05-15 | FIX-VIEW-DUAL-TANK-MODULE-BATCH-START | 생산현황 상세화면 Tank Module 일괄 시작/종료 — DUAL 모델 L/R 2개 중 1개만 시작되던 버그 fix (Twin파파 catch). 원인: SNDetailPanel.tsx 현재 S/N 의 TANK_MODULE task 를 `catTasks.find(isTankModule)` 로 첫 1개만 잡음 → DUAL 모델은 L/R 2개 task 인데 1개만 batch 에 포함. fix: `.find()` → `.filter()` 배열화 (tankTask → tankTasks). parallelDialog state `taskId: number` → `taskIds: number[]`. handleTankStart/Complete 배열 받기 + single(1개)/batch(DUAL 2개) 분기. handleParallelConfirm `ids = [...taskIds, ...others]`. TankModuleActions props `task` → `tasks` 배열. Codex 라운드 1 M=3 반영: (Q2) force_closed/부분상태 — 미시작(startable)/진행중(completable) 분리 → DUAL L 진행중·R 미시작 시 시작·종료 버튼 동시 노출 / (Q6) force_closed task 판정 제외 (activeTasks filter) / (Q4) ParallelConfirmDialog "1대만" → "이 S/N만" 문구 정정. OPS BE 변경 0 (get_tasks_by_order/start_work_batch 정상 — DUAL 2개 반환·배열 처리). 2 파일 (SNDetailPanel.tsx + ParallelConfirmDialog.tsx). tsc -b 에러 0 + vite build GREEN + vitest 62/62 PASS. 회귀 0 (SINGLE 모델 기존 동작 유지, others/다른 S/N 영역 무관)
// v1.43.10| 2026-05-15 | HOTFIX-MECH-CHECKLIST-STATUS | 생산현황 상세화면 MECH 체크리스트 미표시 fix (Twin파파 catch). 원인: api/checklist.ts getChecklistStatus() 의 CAT_MAP 에 MECH 누락 — MECH 체크리스트 BE 엔드포인트(OPS Sprint 63-BE)가 생기기 전 작성된 코드라 MECH BE 추가 후 CAT_MAP 갱신 누락 → MECH 는 항상 EMPTY_CHECKLIST early-return → 상세화면 체크리스트 섹션 미렌더. SNDetailPanel 구조(CHECKLIST_CATEGORIES)는 이미 MECH 포함. fix: CAT_MAP 에 MECH:'mech' 추가. + Codex M-1 동반 fix: 상세 파서 transform 이 id/status/worker_name 기대했으나 BE(TM/ELEC/MECH 공통 _get_checklist_by_category)는 master_id/check_result/checked_by_name 반환 → record 항상 null + master_id 가 배열 index 대체되던 잠재 버그 (TM/ELEC 도 동일 영향). transform 을 BE 실제 필드명 우선 + legacy fallback 으로 정정. 2 파일 (api/checklist.ts CAT_MAP+BeDetailItem+transform / checklist.test.ts 신규 7 TC). BE 변경 0. Codex 1차 NO-GO(M-1) → fix → 2차 GO. 빌드 GREEN + vitest 59/59 PASS (52 + 신규 7)
// v1.43.9| 2026-05-13 | UX Util 명칭 + dropdown 확장 | 자재 마스터/매핑 dropdown 영역 "가스" → "Util" 명칭 변경 + Flow sensor 영역 4종 추가 (PCW-R/BCW/TANK/DRAIN). OPS #64 (admin_materials.py category ILIKE) 배포 완료 후속. 변경: GAS_OPTIONS → UTIL_OPTIONS (전체+LNG+CDA+O2+N2+PCW-R+BCW+TANK+DRAIN 9개) / option 라벨 "가스: X" → "Util: X" / MaterialsPage 테이블 헤더 "가스" → "Util". 2 파일 (MaterialsPage.tsx + ChecklistOptionMapModal.tsx) / ~5 LoC. 빌드 GREEN + vitest 52/52 PASS. 회귀 0 (값 변경 X, 라벨 + dropdown 옵션만 확장)
// v1.43.8| 2026-05-13 | UX case-insensitive + 메시지 정정 | ChecklistEditModal 자재코드 input case-insensitive 매칭 (Twin파파 catch). FE client filter `codeMap` 비교가 case-sensitive 라서 DB 대문자 자재코드(예: 'MFC1234')에 소문자 입력('mfc1234') 시 미등록으로 분류됨 → toLowerCase 정규화. + ChecklistOptionMapModal legacy 경고 메시지 가독성 정정 (Twin파파 catch — "placeholder string 배열 / material_id 배열 / legacy 데이터" 등 개발자 용어 제거 → "⚠️ 이 항목은 이전 형식의 자재 정보가 저장되어 있습니다. 저장 시 선택하신 자재 목록으로 덮어써집니다."). 2 파일 / +5 LoC (ChecklistEditModal codeMap 정규화 + ChecklistOptionMapModal 메시지) + test +24 LoC (case-insensitive 매칭 TC 1건). missing 배열은 원본 입력 보존 (사용자가 입력한 그대로 표시). OPS BE 측 `listMaterials` keyword 검색은 별 repo 영역 (ILIKE 정정 권장). 빌드 GREEN + vitest 52/52 PASS (51 + 신규 1). Severity 사소함 (UX 보강)
// v1.43.7| 2026-05-11 | UX SNDetailPanel  | SNDetailPanel outside-click-to-close + ESC 닫기 (Twin파파 catch). S/N 디테일 사이드 패널 열려있을 때 패널 밖 빈 영역 클릭 시 자동 닫힘 + ESC 키 닫기. ParallelConfirmDialog (모달) 열려있을 때는 모달이 우선 처리 (parallelDialog null 아니면 outside click skip). 1 파일 / +18 LoC (useEscapeKey 재사용 + useRef + useEffect mousedown listener). S/N 카드 클릭 시 onClose + onSelectSerial 양쪽 발동 → React batch 처리 → 자연스럽게 다른 S/N 으로 전환. 빌드 GREEN + vitest 51/51 PASS. Severity 사소함 (UX 보강, 기능 차단 영역 0)
// v1.43.6| 2026-05-11 | HOTFIX-S1-WORKERS | 🚨 S1 긴급 — v1.43.5 후속, by-order 응답 workers 필드 누락으로 인한 상세뷰 흰화면 fix (HOTFIX-TASK-WORKERS-DEFENSIVE-20260511). Twin파파 catch (운영 흰화면 보고). v1.43.5 호환 처리로 orderTasks 가 정상 추출되기 시작 → utils.getTaskCompany 가 task.workers.find() 호출 → BE 응답에 workers 필드 자체 누락 → TypeError → React crash 흰화면. **Severity S1** (전체 상세뷰 사용 불가). FE 단독 즉시 fix (BE 변경 0): `getTasksByOrder` 응답 정규화 (`workers ?? []` 채움) + `utils.getTaskCompany/getOtherSNs...` 이중 안전망 (`Array.isArray(t.workers)` 가드) + `SNDetailPanel.partnerNullCount` 동일 가드. 3 파일 fix (api/snStatus.ts +5 / utils.ts +5 / SNDetailPanel.tsx +6 LoC) + test +24 LoC (workers 누락 응답 정규화 TC). 빌드 GREEN + vitest 51/51 PASS (50 + 신규 1). OPS 측 v2.13.1 동반 — by-order 응답에 workers 포함 필수. Opus 단독 자가 리뷰 → 즉시 패치 (CLAUDE.md L237 S1 정합). 24h 이내 사후 Codex 검토 의무 (deadline 2026-05-12)
// v1.43.5| 2026-05-11 | HOTFIX-SCHEMA     | Sprint 40 일괄 토스트 BE 응답 schema 호환 fix (HOTFIX-TASKS-BY-ORDER-SCHEMA-20260511) — Twin파파 catch. 원인: BE Sprint 64-BE `/api/app/tasks/by-order/{ON}` 응답이 `{tasks, total}` 객체 wrap 인데 FE 는 `SNTaskDetail[]` 배열 직접 응답 가정 → `Array.isArray(data) ? data : []` 가 빈 배열 반환 → `orderTasks=[]` → `getOtherSNsTankStartable=0` → 일괄 모달 미발현 + 단일 호출만 진행. **옵션 B 채택**: VIEW (a) 호환 처리 + OPS v2.13.1 응답 정합 동시 fix (배포 순서 무관). 1 파일 fix (`api/snStatus.ts` getTasksByOrder, +6 LoC — 배열·객체 모두 호환) + 신규 test (`api/snStatus.test.ts` 73 LoC, 3 TC). Codex 사후 검토 누락 영역 (5 라운드 검증 모두 다른 endpoint spec 대조 누락) — POST-REVIEW catch trail. Severity S2 (Sprint 40 핵심 기능 부분 장애). 빌드 GREEN + vitest 50/50 PASS (47 + 신규 3)
// v1.43.4| 2026-05-11 | HOTFIX-EDIT-GUARD | Codex 사후 검토 M-01 + M-02 fix (HOTFIX-CHECKLIST-EDIT-DIRTY-GUARD-20260511) — Task #20 결과 반영. M-01 (Late Hydrate Overwrite): selectDirty flag 도입 → 사용자가 자재코드 input 한 번이라도 건드리면 late hydrate skip (allMaterials 늦게 도착해도 입력값 덮어쓰기 차단). M-02 (옵션 C invariant 미강제): SELECT 항목 + hasPendingSelectChange=false 분기에 기존 select_options 길이 0 차단 guard 추가 (빈 SELECT 항목이 다른 필드만 수정되어 저장되는 경로 차단 → 현장 빈 드롭다운 노출 방지). 1 파일 fix (ChecklistEditModal.tsx +21/-3) + 테스트 +60 LoC (M-02 invariant TC 2건 — 빈 매핑 차단 + 기존 1+개 통과). 빌드 GREEN + vitest 47/47 PASS (45 + 신규 2). Codex Advisory A-01 (부분 성공 롤백) + A-02 (직접 입력 vs 보조 모달 정책 불일치)는 BACKLOG 이관 권장
// v1.43.1| 2026-05-11 | HOTFIX-SPRINT42   | Sprint 42 후속 hotfix — ChecklistEditModal SELECT 항목 자재 매핑 영역 통합 (Twin파파 5-08 UI catch). **방향 A 채택** (BE 변경 0, FE 단독): 자재코드 input + debounce 500ms + client-side filter + FE Map 변환 → PATCH number[] (Sprint 42 Step 4 schema 정합). **옵션 C 강제** (최소 1자재 매핑 + 미등록 자재 차단, toast 안내). HOTFIX-SPRINT66BE 폐기. 신규 2 파일 (useDebounce.ts 20 / ChecklistEditModal.test.tsx 112) + 수정 5 파일 (ChecklistEditModal +180/-14 / ChecklistAddModal +18/-13 / ChecklistOptionMapModal +3/-1 / ChecklistManagePage +10/-8 async handleEdit / types/checklist +2/-1 union). hydrate useEffect (numeric id→item_code) + hydrated flag (사용자 입력 덮어쓰기 차단) + Promise.all 패턴 (race 차단) + master cache invalidate. Severity S2, deadline 사후 Codex 검토 2026-05-18. Codex 1·2·3차 + Claude 5·6차 누적 약 30+건 합의 (cowork 추측 작성 실수 #11~#22 누적, ADR-024 candidate 강한 권장). 빌드 GREEN + vitest 45/45 PASS (기존 42 + 신규 3). ~346 LOC 실측 (신규 132 + 수정 214)
// v1.45.1 | 2026-05-18 | 헤더 메뉴얼 버튼 | 상단바 검색 버튼(onClick 없는 죽은 stub — 전역 검색 기획 후 미구현 placeholder) 제거 + 메뉴얼 버튼 신규. 공지사항·설정 사이 배치, 책 아이콘, 클릭 시 https://axis-manual.netlify.app/ 새 탭 열기(noopener,noreferrer), title="메뉴얼" 툴팁. 새 route/페이지 0 — 외부 URL 링크. Header.tsx 1 파일. 빌드 GREEN + vitest 84/84
// v1.45.0 | 2026-05-18 | Sprint 45 — 생산현황 view/filter 정리 | (A) 테스트 S/N 토글 의미 변경 (옵션 B) — showTestSN ON = 운영+테스트 혼재 → 테스트 전용. matchesTestFilter() 신규 (showTestOnly ? isTest : !isTest). SNStatusSettingsPanel 라벨 "테스트 S/N 표시"→"전용 보기". (B) GST 자체공정 PI/QI/SI role 자동 스코프 — 협력사 view 패턴 확장. is_manager 만 전체, 일반 GST 작업자는 자기 role 공정(PI/QI/SI)만 (진행률 + S/N 목록). companyScopedProgress.ts: UserScope +isManager/role, userToScope() 신규 (호출처 5곳 중복 제거), getCompanyScopedCategories/Percent GST manager(전체)/작업자([role]) 분기. SNStatusPage: isAdminOrGst → seesAll + scope + scopeCats(필터용 — null=전체/[role]/COMPANY_CATEGORIES). edge: GST 작업자 role≠PI/QI/SI → [] → 빈 목록 (전체 fallback 금지, Twin파파 원칙). BE 변경 0 (user.role/is_manager 기존 필드). Codex 1라운드 M2/A3 → 영역 9 명문화 반영. 5 파일 + test 2 (companyScopedProgress 21 TC + SNStatusPage matchesTestFilter 3 TC). 빌드 GREEN + vitest 84/84 PASS
// v1.44.2| 2026-05-18 | FIX-FORCE-CLOSED-REACTIVATION | 강제종료 task 재활성화 버튼 표시 일관성 fix (Twin파파 catch). ProcessStepCard.tsx 재활성화 버튼 조건이 `w.completed_at` 의존 → 작업자가 시작했던 task 강제종료(worker completed_at 채워짐)는 버튼 표시, 미시작 task 강제종료(SNDetailPanel placeholder worker completed_at=null)는 버튼 미표시 → 같은 강제종료인데 버튼 노출 불일치. fix: 조건 `w.completed_at` → `(w.completed_at || w.force_closed)` (1줄). force_closed placeholder 도 재활성화 버튼 노출 — BE reactivate 는 app_task_details.completed_at 기준이라 미시작 강제종료 task(completed_at=강제종료시각 set)도 정상 작동. Codex 라운드 1 Q3=N (노출 범위 정확 — 진행중 worker/정상 미시작 placeholder 는 force_closed=false 라 미노출). 1 파일 (ProcessStepCard.tsx 1줄). BE 변경 동반 = OPS v2.15.20 (reactivate_task 4컬럼 리셋). 회귀 0 (additive 조건 확장)
